src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(length: 255)]
    private ?string $carrierName = null;

    #[ORM\Column]
    private ?float $carrierPrice = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $delivery = null;

    /**
     * @var Collection<int, OrderDetail>
     */
    #[ORM\OneToMany(targetEntity: OrderDetail::class, mappedBy: 'myOrder', cascade:["persist"])]
    private Collection $orderDetails;

    #[ORM\Column]
    private ?int $state = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $stripe_session_id = null;

    public function __construct()
    {
        $this->orderDetails = new ArrayCollection();
    }

    //Calcul total TTC produits + transporteur
    public function getTotalPriceTva()
    {
        $totalTtc = 0;
        $products = $this->getOrderDetails();

        foreach($products as $product){
            $factor = 1 + ($product->getProductTva()/100);
            $totalTtc += ($product->getProductPrice() * $factor) * $product->getProductQuality();
        };

        return $totalTtc + $this->getCarrierPrice();
    }

    //Calcul total TVA
    public function getTotalTva()
    {
        $totalTva = 0;
        $products = $this->getOrderDetails();

        foreach($products as $product){
            $factor = $product->getProductTva()/100;
            $totalTva += $product->getProductPrice() * $factor;
            //dd($product->getProductPrice() * $factor);
        };

        return $totalTva;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrierName;
    }

    public function setCarrierName(string $carrierName): static
    {
        $this->carrierName = $carrierName;

        return $this;
    }

    public function getCarrierPrice(): ?float
    {
        return $this->carrierPrice;
    }

    public function setCarrierPrice(float $carrierPrice): static
    {
        $this->carrierPrice = $carrierPrice;

        return $this;
    }

    public function getDelivery(): ?string
    {
        return $this->delivery;
    }

    public function setDelivery(string $delivery): static
    {
        $this->delivery = $delivery;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetail>
     */
    public function getOrderDetails(): Collection
    {
        return $this->orderDetails;
    }

    public function addOrderDetail(OrderDetail $orderDetail): static
    {
        if (!$this->orderDetails->contains($orderDetail)) {
            $this->orderDetails->add($orderDetail);
            $orderDetail->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetail $orderDetail): static
    {
        if ($this->orderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getMyOrder() === $this) {
                $orderDetail->setMyOrder(null);
            }
        }

        return $this;
    }

    /*
        type de valeur d'état du setstate: 
            1 = en attente du paiement (ou panier abandonné)
            2 = paiement validé
            3 = en cours de prérparation
            4 = commande expédiée
            5 = commande annulé
    */
    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getStripeSessionId(): ?string
    {
        return $this->stripe_session_id;
    }

    public function setStripeSessionId(?string $stripe_session_id): static
    {
        $this->stripe_session_id = $stripe_session_id;

        return $this;
    }
}

src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isFlagship = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    //calcul PRIX et TVA
    public function getPriceTva()
    {
        $factor = 1 + ($this->tva/100);
        return $factor * $this->price;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function isFlagship(): ?bool
    {
        return $this->isFlagship;
    }

    public function setIsFlagship(?bool $isFlagship): static
    {
        $this->isFlagship = $isFlagship;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Address;
use App\Entity\Carrier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('addresses', EntityType::class, [
                "class"=>Address::class,// on défninie quelle entité elle est lié (ici Address)
                "label"=>"Adresse :",
                "attr" => ["placeholder" => "Choisissez votre adresse de livraison"],
                "required" => true,
                "expanded" => true,
                "choices" => $options["addresses"],
                "label_html" => true,//pour interpréter les balise html dans le formulaire (voir orderController)
            ])
            ->add('carriers', EntityType::class, [
                "class"=>Carrier::class,// on défninie quelle entité elle est lié (ici Carrier)
                "label"=>"Transporteur :",
                "attr" => ["placeholder" => "Choisissez votre transporteur de livraison"],
                "required" => true,
                "expanded" => true,
                "label_html" => true,//pour interpréter les balise html dans le formulaire (voir orderController)
            ])
            ->add("submit", SubmitType::class,[
                "label"=>"Valider",
                "attr" => ["class" => "btn btn-dark"],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            "addresses" => null,
        ]);
    }
}

src/Controller/Account/OrderController.php
<?php

namespace App\Controller\Account;

use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class OrderController extends AbstractController
{
    #[Route('/account/order/{id_order}', name: 'app_account_order')]
    public function index($id_order, OrderRepository $orderRepository): Response
    {
        $order = $orderRepository->findOneBy([
            "id" => $id_order,
            "user" => $this->getUser(),
        ]);

        //Si pas de commande, alors redirige vers la page d'accueil
        if (!$order){
            $this->addFlash(
                'danger',//type de notif (couleur success bootstrap)
                'Aucunes commande enregistré. Veuillez en créer une !'//message de la notif
            );
            return $this->redirectToRoute("app_home");
        };
        
        return $this->render('account/order/index.html.twig', [
            'order' => $order,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use DateTime;
use App\Class\Basket;
use App\Entity\Order;
use App\Form\OrderType;
use App\Entity\OrderDetail;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class OrderController extends AbstractController
{
    // ##################################################################### //
    // ############## Étape 1 : choix adresse et transporteur ############## //
    // ##################################################################### //
    #[Route('/order', name: 'app_order')]
    public function index(): Response
    {
        $addresses = $this->getUser()->getAddresses();
        if(count($addresses) == 0){//si pas d'adresse (collection)
            $this->addFlash(
                'danger',//type de notif (couleur success bootstrap)
                'Aucunes adresse enregistré. Veuillez en créer une !'//message de la notif
            );
            return $this->redirectToRoute("app_account_address_form");
        }


        $form = $this->createForm(OrderType::class, null, [
            "addresses" => $addresses,
            "action" => $this->generateUrl("app_order_summary")
        ]);//2eme paramètre c'est le mapping à une entité, le 3eme paramètre sont les options

        return $this->render('order/index.html.twig', [
            'deliveryForm' => $form->createView(),
        ]);
    }


    // ##################################################################### //
    // ################### Étape 2 : Récap de la commande ################## //
    // ##################################################################### //
    #[Route('/order/summary', name: 'app_order_summary')]
    public function add(Request $request, Basket $basket, EntityManagerInterface $entityManager): Response
    {
        $addresses = $this->getUser()->getAddresses();

        if($request->getMethod() != "POST"){
            $this->addFlash(
                'danger', // type de notif (couleur success bootstrap)
                'Accès non autorisé !' // message de la notif
            );
            return $this->redirectToRoute("app_basket");
        }
        
        
        $form = $this->createForm(OrderType::class, null, [
            "addresses" => $addresses = $this->getUser()->getAddresses(),
        ]);
        $products = $basket->getBasket();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $addressObject = $form->get("addresses")->getData();

            $address =  $addressObject->getLastName()." ".$addressObject->getFirstName()."<br/>";
                $address .=  $addressObject->getAddress()."<br/>";
                $address .=  $addressObject->getPostal()." ".$addressObject->getCity()."<br/>";
                $address .=  $addressObject->getCountry()."<br/>";
                $address .=  $addressObject->getPhone();

            //dd($basket);


            $order = new Order();

            $order -> setCreatedAt(new DateTime());
            $order -> setState(1);
            $order -> setCarrierName($form->get("carriers")->getdata()->getName());
            $order -> setCarrierPrice($form->get("carriers")->getdata()->getPrice());
            $order -> setDelivery($address);
            $order -> setUser($this->getUser());

            foreach ($products as $product){
                //dd($product);
                $orderDetail = new OrderDetail();

                $orderDetail -> setProductName($product["object"]->getName());
                $orderDetail -> setProductImage($product["object"]->getImage());
                $orderDetail -> setProductPrice($product["object"]->getPrice());
                $orderDetail -> setProductTva($product["object"]->getTva());
                $orderDetail -> setProductQuality($product["qty"]);//c'est la quantité
                $order -> addOrderDetail($orderDetail);
            }

            $entityManager->persist($order);
            $entityManager->flush();
        }


        
        return $this->render('order/summary.html.twig',[
            "choices" => $form->getData(),
            "basket" => $products,
            "totalPriceTva" => $basket->getTotalPriceTva(),
            "order" => $order,
        ]);
    }
}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container my-5 small-container">

        <h1 class="mb-5">Livraison</h1>
        
        {{ form_start (deliveryForm) }}
            {{ form_row(deliveryForm.addresses) }}
            <a href="{{ path("app_account_address_form")}}" class="btn btn-light"><i class="bi bi-plus-circle-fill"></i></a>
            <hr class="my-5">
            {{ form_row(deliveryForm.carriers) }}
        {{ form_end (deliveryForm) }}

    </div>
{% endblock %}

templates/order/summary.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container my-5">

        <h1 class="mb-5">Résumé de la commande</h1>
        
        <div class="row">

            <div class="col-md-8">
                <strong>Contenu du panier</strong><br>
                {% for product in basket %}
                    <div class="row mb-3">
                        <hr>
                            {# {{dump(product)}} #}
                            <div class="col-md-2">
                                <img src="/uploads/{{ product.object.image }}" class="img-fluid" alt="{{ product.object.name }}">
                            </div>
                            <div class="col-md-5">
                                <strong>
                                    {{ product.object.name }}
                                </strong>
                                <small class="d-block">
                                    P.U. :
                                    {{ product.object.priceTva | pricefilter }}
                                </small>
                            </div>
                            <div class="col-md-3 text-end">
                                <span class="mx-2">x{{ product.qty }}</span>
                            </div>
                            <div class="col-md-2 text-end">
                                <strong>
                                    {{ (product.qty * product.object.priceTva) | pricefilter }}
                                </strong>
                            {# on fait en premier l'opération puis on applique le filtre  #}
                            </div>
                    </div>
                {% endfor %}
                
                <hr>
                
                <strong>Adresse de livraison :</strong><br>
                {{ choices.addresses.lastname}} {{ choices.addresses.firstname}}
                {{ choices.addresses.address}}, {{ choices.addresses.postal}} {{ choices.addresses.city}} - {{ choices.addresses.country}}
                
                <hr>
                
                <strong>Transporteur :</strong><br>
                {{ choices.carriers.name }} - <small>{{ choices.carriers.description }}</small>
            </div>

            <div class="col-md-4">
                <div class="bg-light p-3">
                    <div class="d-flex justify-content-between">
                        <span class="fw-bold">Total articles : </span>
                        <span>{{ totalPriceTva|pricefilter }}</span>
                    </div>
                </div>
                <div class="bg-light p-3">
                    <div class="d-flex justify-content-between">
                        <span class="fw-bold">Total transporteur : </span>
                        <span>{{ choices.carriers.price|pricefilter }}</span>
                    </div>
                </div>
                <div class="bg-light p-3">
                    <div class="d-flex justify-content-between">
                        <span class="fw-bold">Total : </span>
                        <strong>{{ (choices.carriers.price + totalPriceTva)|pricefilter }}</strong>
                    </div>
                <div><a href="{{ path ("app_payment", {"id_order": order.id}) }}" class="btn btn-success w-100 mt-3">Payer</a></div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}